### ISSUE TITLE
Java compatibility issue with kotlin lambda expressions

### ISSUE THREAD

**Issue by locomike** [form-com/diff-coverage-gradle#14]
I'm getting the following error when trying to execute `diffCoverage` task:

```
Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
	at com.form.coverage.report.analyzable.DiffCoverageAnalyzableReport$buildAnalyzer$1.<init>(DiffCoverageAnalyzableReport.kt)
	at com.form.coverage.report.analyzable.DiffCoverageAnalyzableReport.buildAnalyzer(DiffCoverageAnalyzableReport.kt:37)
	at com.form.coverage.report.ReportGenerator$create$bundleCoverage$1.invoke(ReportGenerator.kt:50)
	at com.form.coverage.report.ReportGenerator$create$bundleCoverage$1.invoke(ReportGenerator.kt:16)
```

It seems to be related to https://youtrack.jetbrains.com/issue/KT-39389#focus=Comments-27-4184517.0-0, but I have not found a workaround for it. 

I'm building this for an android project where I'm currently using gradle 6.5 and kotline 4.0. I have tried updating those but I still get this error when executing `diffCoverage`.

It looks like a change like this solves it for me, but I'm not sure this is the right approach:

```diff
diff --git a/jacoco-filtering-extension/src/main/kotlin/com/form/coverage/report/analyzable/DiffCoverageAnalyzableReport.kt b/jacoco-filtering-extension/src/main/kotlin/com/form/coverage/report/analyzable/DiffCoverageAnalyzableReport.kt
index 7b106f2..e913e15 100644
--- a/jacoco-filtering-extension/src/main/kotlin/com/form/coverage/report/analyzable/DiffCoverageAnalyzableReport.kt
+++ b/jacoco-filtering-extension/src/main/kotlin/com/form/coverage/report/analyzable/DiffCoverageAnalyzableReport.kt
@@ -34,7 +34,10 @@ internal class DiffCoverageAnalyzableReport(
         return FilteringAnalyzer(
                 executionDataStore,
                 coverageVisitor,
-                reportMode.codeUpdateInfo::isInfoExists
+            {
+                reportMode.codeUpdateInfo.isInfoExists(it)
+            }
+
         ) {
             ModifiedLinesFilter(reportMode.codeUpdateInfo)
         }
```

**Comment by SurpSG** [comment]
Hi @locomike 
Could you please provide the next info:
* what gradle version do you use?
* do you use kotlin gradle dsl or groovy?

**Comment by locomike** [comment]
This is my `./gradlew --version` output:

```
./gradlew --version

------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.11 (Azul Systems, Inc. 11.0.11+9-LTS)
OS:           Mac OS X 11.4 aarch64
```

I'm using Groovy DSL.

I guess the problem could be tha tI'm using Kotlin 1.3.72 and I need at least 1.4. I will try and figure out how to update that.

**Comment by SurpSG** [comment]
@locomike try to downgrade Diff Coverage from v0.7.2 to v0.7.1, please.
Kotlin v1.3.72 is used in Diff Coverage 0.7.1

**Comment by locomike** [comment]
@SurpSG Thanks, that did it! 

Is there a particular version of Gradle I need to migrate to to have v0.7.2 working? I get that the issue here is the embedded Kotlin inside Gradle, and not my Kotline dependency specified in Gradle, which is above v4.

**Comment by SurpSG** [comment]
@locomike 
Could you please check the fix?
```
classpath 'com.github.form-com.diff-coverage-gradle:diff-coverage:migrate-to-gradle-7-SNAPSHOT'
```
Change version from `0.7.x` -> `migrate-to-gradle-7-SNAPSHOT'`

**Comment by locomike** [comment]
@SurpSG I can confirm the fix works fine for my workspace. Thanks!

Can you link the commit that fixed it?

**Comment by SurpSG** [comment]
Thanks!
we will make a new release with the fix soon.

In v0.7.2 we've updated kotlin plugin to v1.4.32 but Gradle 6.7.1 has embedded kotlin 1.3.72

Adding of 
https://github.com/form-com/diff-coverage-gradle/blob/e4bb5b60cb5e62caa8c9c69bea4be62e9a3bc15b/build.gradle#L54
fixed the issue
```
compileKotlin {
        kotlinOptions.jvmTarget = '1.8'
        kotlinOptions.apiVersion = '1.3' // <----------
    }
```

**Comment by SurpSG** [comment]
Fixed in https://github.com/form-com/diff-coverage-gradle/releases/tag/0.8.0
