### ISSUE TITLE
diff.patch not correctly created when running inside CI

### ISSUE THREAD

**Issue by locomike** [form-com/diff-coverage-gradle#16]
I have configured the project to run correctly locally using `git` configuration to get the `diff`.

This is my configuration:

```groovy
diffCoverageReport {
      def targetBranch = project.getProperties().get("targetBranch") ?: "development"
      diffSource {
          git.compareWith targetBranch
      }

      jacocoExecFiles = files(jacocoTestReport.executionData)
      classesDirs = files(jacocoTestReport.classDirectories)
      srcDirs = files(jacocoTestReport.sourceDirectories)

      reports {
          html = true
          xml = true
      }

      violationRules {
          minBranches = 1
          minLines = 1
          minInstructions = 1
          failOnViolation = true
      }
}
```

However, when I run inside Gitlab CI/CD, the execution fails because it cannot create `diff.patch`. I believe the issue is becuase the folder where it wants to create it, `build/reports/jacoco/`, because if I pre-create this folder empty, then the plugin finishes successfully.

This is the exception:
```
Caused by: java.io.FileNotFoundException: /builds/android/<REPO>/build/reports/jacoco/diff.patch (No such file or directory)
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134)
	at com.form.coverage.tasks.git.GitDiffSource.saveDiffTo(DiffSource.kt:67)
	at com.form.coverage.tasks.DiffCoverageTask.obtainUpdatesInfo(DiffCoverageTask.kt:109)
	at com.form.coverage.tasks.DiffCoverageTask.executeAction(DiffCoverageTask.kt:61)
	at com.form.coverage.tasks.DiffCoverageTask$executeAction.call(Unknown Source)
```

I verified that `/builds/android/<REPO>` exists and it is the root of my project. I also verified that simply running `mkdir -p ./build/reports/jacoco` before running my `gradlew` command fixes it.

Can you help me identify why the folder would be successfully created when running locally but fails when running inside CI?

**Comment by SurpSG** [comment]
Hi @locomike 
Could you please check if the issue is reproducible on this version?
```
'com.github.form-com.diff-coverage-gradle:diff-coverage:precreate-reports-dir-SNAPSHOT'
```

**Comment by locomike** [comment]
That fixed it, thanks so much for the prompt fix!

Any idea why creating the dir is needed in CI but not in Desktop? Maybe some kind of race condition?

**Comment by SurpSG** [comment]
Hi @locomike 
AFAIK Gradle is responsible for creating of the report dir, because the dir is declared as output
https://github.com/form-com/diff-coverage-gradle/blob/1bcb38d66d45fae0b6b79bb6c2bf7aed67ffdd24/diff-coverage/src/main/kotlin/com/form/coverage/tasks/DiffCoverageTask.kt#L49
I wasn't able to reporoduce the issue on my env. We will merge the fix you tested to make sure the output dir exists.
And I have no idea why it works on your local env but doesn't on your CI env.
