### ISSUE TITLE
File Path is not support on UTF8 chars

### ISSUE THREAD

**Issue by kintomiko** [form-com/diff-coverage-gradle#22]
* What went wrong:
Execution failed for task ':diffCoverage'.
> Couldn't parse file relative path: +++ "......./\043\043\043 Fresh Video.json.withOption"

**Comment by SurpSG** [comment]
Hi  @kintomiko 
* Could you provide the diff?
* what tool are you using to generate the diff?
* what the original path of `"......./\043\043\043 Fresh Video.json.withOption"`?

**Comment by kintomiko** [comment]
@SurpSG Thank you for your quick response. Sorry I can't provide the diff, we are using git.compareWith to generate the diff as your example shows

```		
diffSource{
	git.compareWith 'refs/remotes/origin/develop'
}```

\043\043\043 Fresh Video.json.withOption is in our git source code and included in git diff. 
The full message is

`Couldn't parse file relative path: +++ "b/{module}/{package}/\043\043\043 Fresh Video.json.withOption"`

**Comment by SurpSG** [comment]
Hi @kintomiko 

Please check the fix on `develop-SNAPSHOT` version?
```groovy
buildscript {
    repositories {
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.github.form-com.diff-coverage-gradle:diff-coverage:develop-SNAPSHOT'
    }
```

**Comment by kintomiko** [comment]
Thank you will check using my personal computer, get back to you soon 👍  @SurpSG

**Comment by kintomiko** [comment]
@SurpSG yep it works for me, Thank you very much!

Could you pls make a release version? My network block snapshots 😓

**Comment by SurpSG** [comment]
@kintomiko v0.8.1 is released https://github.com/form-com/diff-coverage-gradle/releases/tag/0.8.1
