### ISSUE TITLE
Possible to use with GitLab Violation reporter?

### ISSUE THREAD

**Issue by Poeschl** [form-com/diff-coverage-gradle#33]
Is it possible to use the csv or xml output with https://github.com/tomasbjerre/violation-comments-to-gitlab-gradle-plugin?
Would be nice to have the violations as comments in our GitLab ;)

**Comment by SurpSG** [comment]
Seems, [violation-comments-to-gitlab-gradle-plugin](https://github.com/tomasbjerre/violation-comments-to-gitlab-gradle-plugin) uses [violation-comments-to-gitlab-lib](https://github.com/tomasbjerre/violation-comments-to-gitlab-lib) that:
> It uses `Violation Comments Lib` and supports the same formats as `Violations Lib`

We can see JaCoCo in the list at [violations-lib](https://github.com/tomasbjerre/violations-lib).

`Diff-Coverage` plugin generates html, xml and csv reports that 100% compatible with corresponding JaCoCo repots. 

----

> Is it possible to use the csv or xml output with https://github.com/tomasbjerre/violation-comments-to-gitlab-gradle-plugin?

Seems, yes

**Comment by SurpSG** [comment]
By the way, I suggest to get familiar with gitlab pages and coverage vizualization.

Links:
https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html
https://stackoverflow.com/questions/55732375/how-to-activate-gitlab-pages-in-an-existing-project
https://about.gitlab.com/blog/2016/11/03/publish-code-coverage-report-with-gitlab-pages/
