### ISSUE TITLE
False Negative on Code Coverage for Blank Lines and Comments added to Source file under test

### ISSUE THREAD

**Issue by kingargyle** [form-com/diff-coverage-gradle#61]
**Describe the bug**

If you add just a blank line, or a comment, but no new instructions or functions to a class under test, the coverage violations will fail and say you have not met the threshold.   In this case there is no new instructions, just comments and some extra blank lines, so code coverage should be the same as it was before.

We have instruction coverage to be a minimum of 0.7 percent, and branch coverage for 0.5 percent.  The branch coverage is passing.  The instruction coverage fails

Min Line coverage is 0.0.

       diffCoverageExtension.violationRules{
            minBranches = 0.5 // Optional. Default `0.0`
            minInstructions = 0.7 // Optional. Default `0.0`
            failOnViolation = true // Optional. Default `false`
        }

**Desktop (please complete the following information):**
 - OS:  all
 - Gradle version: 7.4.1
 - Diff Coverage plugin version  = 0.9.5

**To Reproduce**
If possible, provide your configuration of the plugin, for example:
```groovy
diffCoverageReport {
    diffSource.file = 'diff.patch'

    violationRules.failIfCoverageLessThan 0.9
}

// Some comment in a source file 
```

**Expected behavior**

Since no instruction coverage changed this should still pass and meet the original thresholds.

**Comment by SurpSG** [comment]
Hi @kingargyle 

Diff Coverage automatically dumps a diff to build/report/diffCoverage output directory. Please, verify your diff file.
If everything ok with the diff then try to perform diff coverage validation with `clean` gradle task.

If the issue still reproduces then provide please some sample project where I could reproduce the issue.

**Comment by kingargyle** [comment]
Thanks, will try to reproduce the issue in one of my public repos as currently seeing this happening at work.

**Comment by kingargyle** [comment]
Haven't forgotten about this, hopefully I can get something this weekend or next week on one of my public repos.

**Comment by kingargyle** [comment]
Working on the PR today. Sorry for the delay.

**Comment by kingargyle** [comment]
Going to go ahead and close this issue as I can't currently duplicate the issue locally anymore.
