### ISSUE TITLE
How to setup in a multi-module project?

### ISSUE THREAD

**Issue by NapasPayu** [form-com/diff-coverage-gradle#66]
I applied the plugin (v 0.9.5) in the root's `build.gradle`. After generating the reports, `diff.patch` is not correct compared to the result from `git diff`. Looks like it doesn't include diff in submodules. 

Even if I tried configuring the report as below , it still doesn't work as expected.
```
diffCoverageReport {
    ...
    jacocoExecFiles = files(...)
    srcDirs = files(...)
    classesDirs = files(...)      
}
```

It'd be great if you could provide an example for multi-module setup.

**Comment by SurpSG** [comment]
Hi @NapasPayu 

There is a sample project https://github.com/SurpSG/diff-coverage-gradle-example

Please check

**Comment by NapasPayu** [comment]
@SurpSG I've tried on [your sample](https://github.com/SurpSG/diff-coverage-gradle-example) and I can confirm that the diff report only works correctly with the plugin version 0.9.0 (doesn't work with 0.9.1 and above) because `diff.patch` doesn't reflect the change.  Could you take a look?

**Comment by SurpSG** [comment]
Git diff includes staged changes. So, if you change your code without staging then these changes are not present in the diff.

This behavior was introduced by [0.9.1](https://github.com/form-com/diff-coverage-gradle/releases/tag/0.9.1). It's minor side effect of a bug fix
