### ISSUE TITLE
README gives incorrect default report directory

### ISSUE THREAD

**Issue by dbwiddis** [form-com/diff-coverage-gradle#72]
> Could not set unknown property 'reportDir' 

https://github.com/form-com/diff-coverage-gradle/blob/502a2b45eead8a19661e125bbb8903b56b66edc4/README.md?plain=1#L168

Seems the correct property is `baseReportDir` and the default ends with `jacoco` (it appends the `diffCoverage` subdirectory to the base path).

**Comment by SurpSG** [comment]
Done, thank you!
