### ISSUE TITLE
Plugin fails when filtering classes before

### ISSUE THREAD

**Issue by julian-christl** [form-com/diff-coverage-gradle#76]
I hope the project still receives support 👀

**Describe the bug**
When filtering the classDirectories used in the jacoco coverage analysis, gradle fails with `'diffCoverageReport.classesDirs' is not configured`. When removing the `afterEvaluate` section, everything works as intended.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Gradle version: 8.2
 - Diff Coverage plugin version: 0.9.5

**To Reproduce**
Since this occurred in a larger project, I created a small reproduction project:
https://github.com/julian-christl/diffCoverageRepro

1. Clone
2. Checkout `chore/repro`
3. Run `gradle clean test jacocoTestReport diffCoverage`

**Expected behavior**
The tests run through, and the reports get created.

**Logs**
```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':diffCoverage'.
> 'diffCoverageReport.classesDirs' is not configured.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 63ms
```

**Comment by SurpSG** [comment]
Hi @julian-christl 
Seems the project is not maintained. The plugin mostly developed by me, so I decided to make an independent fork: https://github.com/SurpSG/delta-coverage-plugin
Please check the issue using delta-coverage plugin and create a new issue there if any

**Comment by julian-christl** [comment]
Hey @SurpSG,
Thank you for answering. While checking out your fork, I realised that the plugin doesn't do what I thought it did.
I searched for a plugin generating only the coverage changes. But this plugin generates the coverage of the changes.
Small but important difference. Thanks anyway :)
